openapi: 3.1.0
servers:
  - url: https://api.gaiusbot.me
info:
  title: Unofficial API Docs for Gaius Discord Bots
  version: "1.1"
  license:
    name: MIT
    url: https://mit-license.org/
  description: |
    # About
    **Unofficial [Gaius](https://gaiusbot.me) API docs**
    Built by [Flammableassassin](https://github.com/flamableassassin)

    If you wish to contribute feel free to here [https://github.com/flamableassassin/openapi-docs/](https://github.com/flamableassassin/openapi-docs/tree/main/specs/gaius)

    Each group has a link to the discord messages from the original API docs. Join the discord server with this invite: https://discord.gg/C7SxkVh


    <SecurityDefinitions />

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: api-key
      description: |
        Use the `createapikey scope scope` command in your server to get the api key for your server.

        Available scopes:
          - `warnings`
          - `caselogs`
          - `wordlists`
          - `notes`
          - `info`
          - `modlogs`
          - `leveling`

tags:
  - name: wordlist
    description: Endpoints for wordlists
    x-displayName: Wordlist Endpoints
  - name: images
    description: Get a random picture
    x-displayName: Image Endpoints
  - name: caselogs
    description: Endpoint for case logs
    x-displayName: Cage logs Endpoints
  - name: warnings
    description: Endpoints for fetching warnings
    x-displayName: Warnings Endpoints
  - name: modlogs
    description: Endpoints for modlogs
    x-displayName: Modlogs
  - name: notes
    description: Endpoints for fetching user notes
    x-displayName: Note Endpoints
  - name: leveling
    description: Endpoints for the Leveling system
    x-displayName: Leveling System Endpoints
  - name: other
    description: Other endpoints
    x-displayName: Other Endpoints
paths:
  /wordlist:
    get:
      tags:
        - wordlist
      summary: Get a list of all wordlists
      security:
        - apiKey:
            - wordlists
  /wordlist/{ListName}:
    description: Deletes the given list if no array of words provided.
    get:
      tags:
        - wordlist
      summary: Get all words in a list
      security:
        - apiKey:
            - wordlists
    put:
      tags:
        - wordlist
      summary: Creates new list with given name optional array of words can be put in the body.
      security:
        - apiKey:
            - wordlists
    patch:
      tags:
        - wordlist
      summary: Update a created list with the words
      security:
        - apiKey:
            - wordlists
    delete:
      tags:
        - wordlist
      summary: Delete words from a list
      security:
        - apiKey:
            - wordlists
  /images/snek:
    get:
      tags:
        - images
      security:
        - apiKey: []
        - {}
      summary: Get a random picture of a snake
  /images/bunny:
    get:
      tags:
        - images
      security:
        - apiKey: []
        - {}
      summary: Get a random picture of a bunny
  /images/guts:
    get:
      tags:
        - images
      security:
        - apiKey: []
        - {}
      summary: Get a random picture of Guts from 'Berserk'
  /images/holo:
    get:
      tags:
        - images
      security:
        - apiKey: []
        - {}
      summary: Get a random picture of Holo from 'Spice and Wolf'
  /images/frieza:
    get:
      tags:
        - images
      security:
        - apiKey: []
        - {}
      summary: Get a random picture of Frieza from 'Dragon Ball'
  /images/seaslug:
    get:
      tags:
        - images
      security:
        - apiKey: []
        - {}
      summary: Get a random picture of a Sea slug
  /caselogs/all:
    get:
      tags:
        - caselogs
      summary: Get all caselogs
      security:
        - apiKey:
            - caselogs
  /caselogs/{UserID}:
    get:
      tags:
        - caselogs
      summary: Fetch caselogs for user with their ID
      description: Fetch all caselogs for a user ID
      security:
        - apiKey:
            - caselogs
  /caselogs/after/{Time}:
    get:
      tags:
        - caselogs
      summary: Get all caselogs that occurred after the given date.
      description: "Get all caselogs that occurred after the given timestamp or ISO date. Invalid dates are: before 2016, and 1 minute after the current time"
      security:
        - apiKey:
            - caselogs
  /caselogs/before/{Time}:
    get:
      tags:
        - caselogs
      summary: Get all caselogs that occurred before the given date.
      description: "Get all caselogs that occurred before the given timestamp or ISO date. Invalid dates are: before 2016, and 1 minute after the current time"
      security:
        - apiKey:
            - caselogs
  /warnings/all:
    get:
      summary: Get all warnings for the given server.
      tags:
        - warnings
      security:
        - apiKey:
            - warnings
  /warnings/{query}:
    get:
      summary: Fetch warning with ID
      description: Fetch all warnings for a user ID or the warning with the corresponding ID
      tags:
        - warnings
      security:
        - apiKey:
            - warnings
  /warnings/after/{Time}:
    get:
      tags:
        - warnings
      summary: Get all warnings that occurred after date.
      description: "Get all warnings that occurred after the given timestamp or ISO date. Invalid dates are: before 2016, and 1 minute after the current time"
      security:
        - apiKey:
            - warnings
  /warnings/before/{Time}:
    get:
      tags:
        - warnings
      summary: Get all warnings that occurred before date.
      description: "Get all warnings that occurred before the given timestamp or ISO date. Invalid dates are: before 2016, and 1 minute after the current time"
      security:
        - apiKey:
            - warnings
  /modlogs/all:
    get:
      tags:
        - modlogs
      summary: Fetch all modlogs
      security:
        - apiKey:
            - modlogs
  /modlogs/{UserID}:
    get:
      tags:
        - modlogs
      summary: Fetch modlogs for user with their ID
      description: Fetch all modlogs for a user ID
      security:
        - apiKey:
            - modlogs
  /notes/all:
    get:
      tags:
        - notes
      security:
        - apiKey:
            - notes
      summary: Get all notes for a given server.
  /notes/{query}:
    get:
      tags:
        - notes
      security:
        - apiKey:
            - notes
      summary: Fetch note with ID
      description: Fetch all notes for a user ID or the note with the corresponding ID
  /user/{User}:
    get:
      tags:
        - other
      summary: Get user information
      security:
        - apiKey:
            - info
  /xp/{userid}:
    get:
      summary: Get a users xp
      tags:
        - leveling
      security:
        - apiKey:
            - leveling
    patch:
      summary: Update a users xp
      tags:
        - leveling
      security:
        - apiKey:
            - leveling