# Yoink from https://github.com/flamableassassin/drawshield-api/blob/main/.github/workflows/test-deploy.yml


# Yoink from https://docusaurus.io/docs/deployment#deploying-to-github-pages
name: Test deployment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

concurrency: preview-${{ github.ref }}

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci
      - name: Test build website
        if: github.event.action != 'closed'
        run: npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build